INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('SON','Sonae, SGPS, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('BCP','Banco Comercial PortuguÃªs, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('BKESY','Banco Espirto Santo E','American Depositary Receipt','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('BSLBA','SLB 3,75% 20MAY22','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('BSINA','SIC 4,5% 11JUL22','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('BSCPH','SCP 5,25% 26NOV21','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('EDP','EDP - Energias de Portugal, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('GALP','Galp Energia, SGPS, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('JRONY','Jeronimo Martins, SGPS, SA','American Depositary Receipt','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('OTEO','Portugal 4.95% SNR BDS 25/10/2023 EUR0.01 REGS','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('RENE','REN - Redes EnergÃ©ticas Nacionais, SGPS, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('SCT','Toyota Caetano Portugal, S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('SNG','Sonagi, S.G.P.S., S.A.','EQUITY','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ZONNF','Nos SGPS SA','Common Stock','webSite','Portugal','Portugues');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AACG','ATA Creativity Global','Depositary Receipt','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AACQ','Artius Acquisition Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAL','American Airlines Group Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAME','Atlantic American Corporation','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAOI','Applied Optoelectronics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAOI','Applied Optoelectronics, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAON','AAON Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAWW','Atlas Air Worldwide Holdings Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAXN','Axon Enterprise Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCB','Ameris Bancorp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCL','AbCellera Biologics Inc','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCM','Abcam PLC','American Depositary Receipt','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABEO','Abeona Therapeutics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABGI','ABG Acquisition Corp. I','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABIO','ARCA biopharma, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABIO','ARCA biopharma Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABMD','ABIOMED Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABNB','Airbnb, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABST','Absolute Software Corporation','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABTX','Allegiance Bancshares Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABUS','Arbutus Biopharma Corp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAC','Acies Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAD','ACADIA Pharmaceuticals Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAH','Atlantic Coastal Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAM','Acamar Partners Acquisition Corp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAMU','Acamar Partners Acquisition Corp','Unit','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACBA','Ace Global Business Acquisition Limited','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACBI','Atlantic Capital Bancshares Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACCD','Accolade Inc','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACER','Acer Therapeutics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACER','Acer Therapeutics Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACET','Adicet Bio, Inc.','Common Stock','webSite','United States','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACET','Adicet Bio, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACEV','ACE Convergence Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACEV','ACE Convergence Acquisition Corp','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO Empresa (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACGL','Arch Capital Group Ltd','Common Stock','webSite','United States','Dow Jones');
